### PR TITLE
fix: ACNA-4162 - add constructor options to set log level and logRetryAfterSeconds

### LINKED ISSUE #101: add way to enable debug logging for other libraries that use this as a dependency
Right now debug logging is only enabled via process.env.DEBUG being set
Add something in options/constructor for HttpExponentialBackoff and ProxyFetch

Related: https://jira.corp.adobe.com/browse/ACNA-4162

### PR DESCRIPTION
**Pull request by shazron**
Closes #101 
Closes #99

Related: https://github.com/adobe/aio-lib-core-networking/pull/102

## Description

Currently the log level can be set by setting the env var `LOG_LEVEL` only which may be less intuitive to set in serverless environments. Also a logRetryAfter setting is added - the number of seconds after which to log a warning if the Retry-After header is greater than the number of seconds. Set to 0 to disable.

Allow dependent callers of this library to set the log level via their respective constructors - for example @adobe/aio-lib-state library.

## Related Issue

See #101 

## How Has This Been Tested?

- npm test

- used this code:
```javascript
const { createFetch, HttpExponentialBackoff } = require('@adobe/aio-lib-core-networking'); // from the branch code
const LOG_LEVEL = 'debug'; // set to 'info' not to see any retries, etc

const proxyFetch = createFetch({ 
    proxyUrl: 'http://localhost:8888',
    logLevel: LOG_LEVEL
})

const httpExponentialBackoff = new HttpExponentialBackoff({
    maxRetries: 3,
    initialDelay: 1000,
    maxDelay: 10000,
    logLevel: LOG_LEVEL,
});

async function main() {
    const response = await proxyFetch('https://www.google.com');
    console.log('ProxyFetch response: ', response.status);
    // this should fail, and retry, and if LOG_LEVEL is debug, it should show debug logs
    const response2 = await httpExponentialBackoff.exponentialBackoff('https://somegibberishurl.com', {});
    console.log('HttpExponentialBackoff response: ', response2.status);
}

main();
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by sandeep-paliwal — APPROVED** [review]

**Review by pru55e11 — APPROVED** [review]

File: src/HttpExponentialBackoff.js [hunk 1]
```diff
@@ -32,6 +32,19 @@ const { createFetch, parseRetryAfterHeader } = require('./utils')
...
 class HttpExponentialBackoff {
+  /**
+   * Creates an instance of HttpExponentialBackoff
+   *
+   * @param {object} [options] configuration options
+   * @param {string} [options.logLevel] the log level to use (default: process.env.LOG_LEVEL or 'info')
+   * @param {number} [options.logRetryAfterSeconds] the number of seconds after which to log a warning if the Retry-After header is greater than the number of seconds. Set to 0 to disable.
+   */
+  constructor (options = {}) {
+    this.logLevel = options.logLevel || process.env.LOG_LEVEL || 'info'
```
Comment (purplecabbage) [inline src/HttpExponentialBackoff.js:43]: why keep this property? looks like its only used to initialize this.logger

**Review by purplecabbage — APPROVED** [review]
